#!/bin/bash

# It's a 🚧 work in progress

eval $(cat $(dirname "$0")/venusia.config)


: '
---------------------------------------------------
 Venusia
---------------------------------------------------
Venusia is a kind of wasm modules registry
Commands:
- procyonctl venusia publish ../hey/hey.wasm hey 0.0.0
- procyonctl venusia delete hey v0.0.0
- procyonctl venusia download hey v0.0.0
- procyonctl venusia list
- procyonctl venusia help
'

# TODO: something like I did with wapm
function venusia_publish() {
  wasm_file=$1
  module_name=$2
  module_version=$3
  data="${module_name}-${module_version}.wasm"
  curl -v \
    -F "file=@${wasm_file}" \
    -F "name=${data}" \
    -H "Content-Type: multipart/form-data" \
    -X POST ${VENUSIA_URL}/wasm/upload
}

function venusia_delete() {
  wasm_file=$1
  curl -v \
	-X DELETE ${VENUSIA_URL}/wasm/delete/${wasm_file}
}

function venusia_download() {
  wasm_file=$1
  curl ${VENUSIA_URL}/wasm/download/${wasm_file} --output ${wasm_file}
}

function venusia_modules_list() {
  curl ${VENUSIA_URL}/wasm/list
}

if [[ "$1" == "venusia" ]]; then

  if [[ "$2" == "help" ]]; then
    echo "🚧 work in progress"
    exit 0
  fi


  if [[ "$2" == "url" ]]; then
    echo "🌍 venusia url: ${VENUSIA_URL}"
    exit 0
  fi

  if [[ "$2" == "publish" ]]; then
    wasm_file=$3
    module_name=$4
    module_version=$5
    if [[ "$module_version" == "" ]]; then
      module_version="default"
    fi
    venusia_publish ${wasm_file} ${module_name} ${module_version}
    exit 0
  fi

  if [[ "$2" == "list" ]]; then
    venusia_modules_list
    exit 0
  fi


  if [[ "$2" == "delete" ]]; then
    module_name=$3
    module_version=$4
    venusia_delete ${module_name}-${module_version}.wasm
    exit 0
  fi

  if [[ "$2" == "download" ]]; then
    module_name=$3
    module_version=$4
    if [[ "$module_version" == "" ]]; then
      module_version="default"
    fi
    venusia_download ${module_name}-${module_version}.wasm
    exit 0
  fi

  echo "🤔 please try again, I don't understand"
fi