#!/bin/bash

# It's a 🚧 work in progress

eval $(cat $(dirname "$0")/venusia.config)


: '
---------------------------------------------------
 Venusia
---------------------------------------------------
Venusia is a kind of wasm modules registry
Commands:
- ./venusiactl publish satellites/forty-two/forty-two.wasm forty-two 0.0.0
  ./venusiactl publish satellites/hello-world-1.0.1/hello-world.wasm forty-two 1.0.1
  ./venusiactl publish satellites/hello-world-1.0.2/hello-world.wasm forty-two 1.0.2
- venusiactl delete hey v0.0.0
- venusiactl download hey v0.0.0
- venusiactl list
- venusiactl venusia help
'

function venusia_publish() {
  wasm_file=$1
  module_name=$2
  module_version=$3
  data="${module_name}-${module_version}.wasm"
  curl -v \
    -F "file=@${wasm_file}" \
    -F "name=${data}" \
    -H "Content-Type: multipart/form-data" \
    -X POST ${VENUSIA_URL}/wasm/upload
}

function venusia_delete() {
  wasm_file=$1
  curl -v \
	-X DELETE ${VENUSIA_URL}/wasm/delete/${wasm_file}
}

function venusia_download() {
  wasm_file=$1
  curl ${VENUSIA_URL}/wasm/download/${wasm_file} --output ${wasm_file}
}

function venusia_modules_list() {
  curl ${VENUSIA_URL}/wasm/list
}


if [[ "$1" == "help" ]]; then
  echo "🚧 work in progress"
  exit 0
fi


if [[ "$1" == "url" ]]; then
  echo "🌍 venusia url: ${VENUSIA_URL}"
  exit 0
fi

if [[ "$1" == "publish" ]]; then
  wasm_file=$2
  module_name=$3
  module_version=$4
  if [[ "$module_version" == "" ]]; then
    module_version="default"
  fi
  venusia_publish ${wasm_file} ${module_name} ${module_version}
  exit 0
fi

if [[ "$1" == "list" ]]; then
  venusia_modules_list
  exit 0
fi


if [[ "$1" == "delete" ]]; then
  module_name=$2
  module_version=$3
  venusia_delete ${module_name}-${module_version}.wasm
  exit 0
fi

if [[ "$1" == "download" ]]; then
  module_name=$2
  module_version=$2
  if [[ "$module_version" == "" ]]; then
    module_version="default"
  fi
  venusia_download ${module_name}-${module_version}.wasm
  exit 0
fi

echo "🤔 please try again, I don't understand"
